<<<<<<< HEAD
name: MCDawn
main: com.mcdawn.full.MCDawn
version: 1.0.0
authors: [jonnyli1125, Incedo]
website: http://full.mcdawn.com/

commands:
    help:
        description: Displays the help menu.
        aliases: [helpop, commands, commandlist, cmdlist]
        permission: mcdawn.*;
        usage: /help <category/command>
    global:
        description: Send a message to all MCDawn servers that are connected to Global Chat.
        aliases: [gl, gc]
        permission: mcdawn.*
        usage: /global <message>
    say:
        description: Broadcast a message to the whole server.
        aliases: [broadcast]
        permission: mcdawn.*
        usage: /say <message>
    kick:
        description: Kick a player from the server
        aliases: 
        permission:
        usage: /kick <player>
    players:
        description: Gets the current online players
        aliases: [p]
        permission:
        usage: /players

permissions:
    mcdawn.*:
        description: Gives you access to ALL the MCDawn commands
        children:
            mcdawn.test: true
            
    mcdawn.test:
        description: Test command
        default: true
=======
name: DawnCraft
main: com.mcdawn.dawncraft.Main
version: 1.0
commands:
   pl:
      description: Used for testing
      usage: /test <option>
      permission:
      permission-message: This is an error
   place:
      description: Places a block at your feet
      usage: /test <option>
      permission:
      permission-message: This is an error
   mark:
      description: Used for marking
      usage: /test <option>
      permission:
      permission-message: This is an error
   s:
      description: Used for testing
      usage: /test <option>
      permission:
      permission-message: This is an error
   select:
      description: Used for testing
      usage: /test <option>
      permission:
      permission-message: This is an error
   summon:
      description: Used for testing
      usage: /test <option>
      permission:
      permission-message: This is an error
   help:
      description: Used for testing
      usage: /test <option>
      permission:
      permission-message: This is an error
   tp:
      description: Used for testing
      usage: /test <option>
      permission:
      permission-message: This is an error
   teleport:
      description: Used for testing
      usage: /test <option>
      permission:
      permission-message: This is an error
   tphere:
      description: Used for testing
      usage: /test <option>
      permission:
      permission-message: This is an error
   teleporthere:
      description: Used for testing
      usage: /test <option>
      permission:
      permission-message: This is an error
   kick:
      description: Used for testing
      usage: /test <option>
      permission:
      permission-message: This is an error
   broadcast:
      description: Used for testing
      usage: /test <option>
      permission:
      permission-message: This is an error
   say:
      description: Used for testing
      usage: /test <option>
      permission:
      permission-message: This is an error
   cuboid:
      description: Used for testing
      usage: /test <option>
      permission:
      permission-message: This is an error
   z:
      description: Used for testing
      usage: /test <option>
      permission:
      permission-message: This is an error
   box:
      description: Used for testing
      usage: /test <option>
      permission:
      permission-message: This is an error
   devs:
      description: Used for testing
      usage: /test <option>
      permission:
      permission-message: This is an error
   developers:
      description: Used for testing
      usage: /test <option>
      permission:
      permission-message: This is an error
   k:
      description: Used for testing
      usage: /test <option>
      permission:
      permission-message: This is an error
   test:
      description: Used for testing
      usage: /test <option>
      permission:
      permission-message: This is an error
>>>>>>> upstream/master
